using System;

namespace Classes {

    /// <summary>
    /// Creating a public class.
    /// </summary>
    public class Book {

        // underscore is used as a convention to show private members.
        // By default things are private
        string _name;
        string _author;
        int _pagecount;

        public Book(string name, string author, int pagecount){
            _name = name;
            _author = author;
            _pagecount = pagecount;
        }

        public void getDescription(){
            Console.WriteLine($"Name : {_name}, Author : {_author}, Pages : {_pagecount}");
        }

        // 'Backing Field'
        public string Name {
            get {
                return _name;
            }
            set {
                _name = value;
            }
        }

        // "Expression Bodied" -> shorthand way
        public string Author {
            get => _author;
            set => _author = value;
        }
        public int Pagecount {
            get => _pagecount;
            set => _pagecount = value;
        }

        // Get Computer "value"
        public string Description {
            get => $"{Name} by {Author}, for {Pagecount} pages.";
        } 

        // Autogenerated. 
        public string ISBN {
            get; set;
        }
        public decimal Price {
            get; set;
        }
    }

} 